### ISSUE TITLE
Finish Buildicus Concierge (now Edit LLC Web Shop) flyer

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/edit-web-shop#1]
Joel, we're rebranding "Buildicus Concierge". For now, let's call it "Edit LLC Web Shop". Move forward with the understanding that this name could change. You'll still need to incorporate the final paragraph Irma mentioned in her previous email. I'll update the github issue for all this.

Until Richard or Irma come in with a new deadline, let's plan to have the changes to the flyer done by next Wednesday 12/16. 

Finally, Joel, please use this blurb at the end of the flyer in place of the lorem ipsum:

>​</> Edit LLC focuses a great deal on mentorship and on growing our local talent pool. "A rising tide lifts all boats," and that's exactly what we aim to do with our approach to building websites for small businesses like yours. We pair fresh talent, consisting of​ ​just-out-of-class designers and developers with seasoned professionals to give the inexperienced that real-world exposure they need to take the next step in their careers. To your benefit, this allows us to build cutting edge, professional sites at a fraction of the cost you'd pay elsewhere. By having your website built by </> Edit LLC,​ you're directly contributing to the future success of these individuals and our community as a whole.

Here is the drive link to the flyer: 
https://drive.google.com/drive/folders/0B8EN2ZGYf3v5dWNHam1kTk9ibHc

due:
12-17-15    11a

**Comment by jperez4509** [comment]
![editllc-webshop-flyer-v1](https://cloud.githubusercontent.com/assets/8659273/11804444/b5e03380-a2b8-11e5-92a4-35592baefe76.jpg)


This is the new design for the flyer. I used the Edit logo and colors. I know the deadline is not until a couple of days from now so I will create another option for you.

**Comment by irms** [comment]
I <3 @jperez4509

**Comment by rodneystrong** [comment]
Excellent work Joel, really like how you stuck with the color constraints and still successfully used complementary colors. 
I'd like your opinion on my video feedback: http://somup.com/colo3B3Ve

**Comment by jperez4509** [comment]
VERSION 2:
![editllc-webshop-flyer-v2](https://cloud.githubusercontent.com/assets/8659273/11829015/4ce5fe5a-a34e-11e5-95f2-71d6d87fe54f.jpg)


VERSION 3:
![editllc-webshop-flyer-v3](https://cloud.githubusercontent.com/assets/8659273/11829022/58226cae-a34e-11e5-825c-29aa836e2d1e.jpg)


VERSION 4:
![editllc-webshop-flyer-v4](https://cloud.githubusercontent.com/assets/8659273/11829025/63dc5906-a34e-11e5-9057-ddd94dc85517.jpg)

**Comment by rodneystrong** [comment]
These are good Joel, good job. 

Can you tell me why you chose a different shade of red for the "Our Process" section? Or specifically *that* shade of red in Version 2? 

Also, please implement a version I mentioned in the video feedback. Use Version 3 to create a Version 5 that also has the red background color.

**Comment by jperez4509** [comment]
@rodneystrong: on Version 2 I used the specific shade of red because that is one of the colors that the Edit logo has. It has a dark red, a light red, and black. I used the light red in the Header Text and the top bar. When I saw it originally in my screen it didn't look as light, now that I see it I do not think it looks good.

**Comment by jperez4509** [comment]
VERSION 5:
![editllc-webshop-flyer-v5](https://cloud.githubusercontent.com/assets/8659273/11835197/567700c0-a387-11e5-95a4-d9db7d093bfa.jpg)

**Comment by jperez4509** [comment]
VERSION 6:
![editllc-webshop-flyer-v6](https://cloud.githubusercontent.com/assets/8659273/11835540/3f07d2d2-a389-11e5-80c7-a5e29a2271a3.jpg)

**Comment by rodneystrong** [comment]
Good shit dude. Thanks for doing  v5 and v6. 

Assigning to @irms now for approval.

**Comment by irms** [comment]
I like version 5! Can you make sure the file goes through pre-flight so we're not sending giant files over email to potential clients?

**Comment by rodneystrong** [comment]
got it @irms 

@jperez4509 this is back on you. Please put the .ai file in the drive folder: https://drive.google.com/drive/folders/0B8EN2ZGYf3v5dWNHam1kTk9ibHc and export version 5 as a PDF and JPG. Try to optimize both files to be under 100kb each if possible without sacrificing too much noticeable quality. 

I know I've got you on a tight deadline for the Anmmar site, but please complete this by 12-17-15  2p

**Comment by rodneystrong** [comment]
Once you've uploaded them, notify irma on this issue and close it.

**Comment by jperez4509** [comment]
@rodneystrong @irms - The Edit llc flyer has been save to the Google Drive. I have uploaded the ai, pdf, and jpg files.

**Comment by irms** [comment]
Thanks, @jperez4509!
