### ISSUE TITLE
Modify flyer

### ISSUE THREAD

**Issue by irms** [EditLLC/edit-web-shop#3]
Would you mind changing "Web Shop" to "Web Design" and making a second version with the following phone number on it:

559-824-6476

Thank you!

@rodneystrong I assigned this to @jperez4509 but let me know if this needs to be reassigned. Your call, of course.

**Comment by rodneystrong** [comment]
Joel, would you be able to get this done by 12-22-15   4p?

**Comment by jperez4509** [comment]
Version 1 (new Web Design name and old number):
![editllc-webshop-flyer-v5-1](https://cloud.githubusercontent.com/assets/8659273/11965914/eda89862-a8ac-11e5-80ca-9a6b2019e1fb.jpg)

Version 2 (new Web Design name and new number):
![editllc-webshop-flyer-v5-2](https://cloud.githubusercontent.com/assets/8659273/11965921/fb9bbeae-a8ac-11e5-8c2d-cbb7d4fdd8ae.jpg)


I have upload the ai, jpg, and pdf to the Google Drive.

**Comment by irms** [comment]
Almost. The phone number in the footer needs to change too, please!

**Comment by jperez4509** [comment]
Sorry about that @irms. I have updated the phone number on the footer. It has also been saved in the Google Drive.

![editllc-webshop-flyer-v5-2 revised](https://cloud.githubusercontent.com/assets/8659273/12041288/d68e4f6e-ae24-11e5-924f-7d3ffd23e784.jpg)

**Comment by irms** [comment]
Where? I don't see an update.

**Comment by jperez4509** [comment]
https://drive.google.com/file/d/0B8EN2ZGYf3v5U1I3cGxDN0pLSUE/view?usp=sharing

The file name is editllc-webshop-flyer-v5-2(revised).jpg and editllc-webshop-flyer-v5-2(revised).pdf

**Comment by irms** [comment]
Thanks!
